### =========================================================================
### denyregions metadata
### -------------------------------------------------------------------------
###

meta <- data.frame(
    Title = c("ce10.Kundaje.ce10-blacklist.rds", 
              "dm3.Kundaje.dm3-blacklist.rds", 
              "hg19.Bernstein.Mint_Blacklist_hg19.rds", 
              "hg19.Birney.wgEncodeDacMapabilityConsensusExcludable.rds", 
              "hg19.Crawford.wgEncodeDukeMapabilityRegionsExcludable.rds", 
              "hg19.Wold.hg19mitoblack.rds", 
              "hg19.Yeo.eCLIP_blacklistregions.hg19.rds", 
              "hg38.Bernstein.Mint_Blacklist_GRCh38.rds", 
              "hg38.Kundaje.GRCh38.blacklist.rds", 
              "hg38.Kundaje.GRCh38_unified_blacklist.rds", 
              "hg38.Reddy.wgEncodeDacMapabilityConsensusExcludable.hg38.rds", 
              "hg38.Wold.hg38mitoblack.rds", 
              "hg38.Yeo.eCLIP_blacklistregions.hg38liftover.bed.fixed.rds", 
              "mm10.Hardison.blacklist.full.rds", 
              "mm10.Hardison.psublacklist.mm10.rds", 
              "mm10.Kundaje.anshul.blacklist.mm10.rds", 
              "mm10.Kundaje.mm10.blacklist.rds", 
              "mm10.Wold.mm10mitoblack.rds", 
              "mm9.Wold.mm9mitoblack.rds"),
    Description = c("Exclusion regions for ce10 by Anshul Kundaje, Stanford", 
                    "Exclusion regions for dm3 by Anshul Kundaje, Stanford", 
                    "Exclusion regions for hg19 by Bradley Bernstein, Broad", 
                    "Exclusion regions for hg19 by Ewan Birney, EBI", 
                    "Exclusion regions for hg19 by Gregory Crawford, Duke", 
                    "Exclusion regions for hg19 by Barbara Wold, Caltech", 
                    "Exclusion regions for hg19 by Gene Yeo, UCSD", 
                    "Exclusion regions for hg38 by Bradley Bernstein, Broad", 
                    "Exclusion regions for hg38 by Anshul Kundaje, Stanford", 
                    "Exclusion regions for hg38 by Anshul Kundaje, Stanford", 
                    "Exclusion regions for hg38 by Tim Reddy, Duke", 
                    "Exclusion regions for hg38 by Barbara Wold, Caltech", 
                    "Exclusion regions for hg38 by Gene Yeo, UCSD", 
                    "Exclusion regions for mm10 by Ross Hardison, PennState", 
                    "Exclusion regions for mm10 by Ross Hardison, PennState", 
                    "Exclusion regions for mm10 by Anshul Kundaje, Stanford", 
                    "Exclusion regions for mm10 by Anshul Kundaje, Stanford", 
                    "Exclusion regions for mm10 by Barbara Wold, Caltech", 
                    "Exclusion regions for mm9 by Barbara Wold, Caltech"),
    BiocVersion = rep("3.14", 19),
    Genome = c("ce10", 
               "dm3", 
               "hg19", 
               "hg19", 
               "hg19", 
               "hg19", 
               "hg19", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "hg38", 
               "mm10", 
               "mm10", 
               "mm10", 
               "mm10", 
               "mm10", 
               "mm9"),
    SourceType = rep("RDS", 19),
    SourceUrl = rep("https://drive.google.com/drive/folders/124DZtsU0YVWqkb7dgu8Nk6b3N8-ShVSC?usp=sharing", 19),
    SourceVersion = rep("May 26 2021", 19),
    Species = c("Caenorhabditis elegans", "Drosophila melanogaster", rep("Homo sapiens", 11), rep("Mus musculus", 6)),
    TaxonomyId = c(6239, 47, rep(9606, 11), rep(10090, 6)),
    Coordinate_1_based = rep(TRUE, 19),
    DataProvider = c(rep("mitra.stanford.edu/kundaje/akundaje/release/blacklists/", 2), rep("ENCODE", 17)),
    Maintainer = rep("Mikhail Dozmorov <mikhail.dozmorov@gmail.com>", 19),
    RDataClass = rep("GRanges", 19),
    DispatchClass = rep("RDS", 19),
    RDataPath = c("ce10.Kundaje.ce10-blacklist.rds", 
                  "dm3.Kundaje.dm3-blacklist.rds", 
                  "hg19.Bernstein.Mint_Blacklist_hg19.rds", 
                  "hg19.Birney.wgEncodeDacMapabilityConsensusExcludable.rds", 
                  "hg19.Crawford.wgEncodeDukeMapabilityRegionsExcludable.rds", 
                  "hg19.Wold.hg19mitoblack.rds", 
                  "hg19.Yeo.eCLIP_blacklistregions.hg19.rds", 
                  "hg38.Bernstein.Mint_Blacklist_GRCh38.rds", 
                  "hg38.Kundaje.GRCh38.blacklist.rds", 
                  "hg38.Kundaje.GRCh38_unified_blacklist.rds", 
                  "hg38.Reddy.wgEncodeDacMapabilityConsensusExcludable.hg38.rds", 
                  "hg38.Wold.hg38mitoblack.rds", 
                  "hg38.Yeo.eCLIP_blacklistregions.hg38liftover.bed.fixed.rds", 
                  "mm10.Hardison.blacklist.full.rds", 
                  "mm10.Hardison.psublacklist.mm10.rds", 
                  "mm10.Kundaje.anshul.blacklist.mm10.rds", 
                  "mm10.Kundaje.mm10.blacklist.rds", 
                  "mm10.Wold.mm10mitoblack.rds", 
                  "mm9.Wold.mm9mitoblack.rds"),
    Tags = c(paste("ce10;Anshul Kundaje;Stanford;exclusion;blacklisted"),
             paste("dm3;Anshul Kundaje;Stanford;exclusion;blacklisted"),
             paste("hg19;Bradley Bernstein;Broad;exclusion;blacklisted"),
             paste("hg19;Ewan Birney;EBI;exclusion;blacklisted"),
             paste("hg19;Gregory Crawford;Duke;exclusion;blacklisted"),
             paste("hg19;Barbara Wold;Caltech;exclusion;blacklisted"),
             paste("hg19;Gene Yeo;UCSD;exclusion;blacklisted"),
             paste("hg38;Bradley Bernstein;Broad;exclusion;blacklisted"),
             paste("hg38;Anshul Kundaje;Stanford;exclusion;blacklisted"),
             paste("hg38;Anshul Kundaje;Stanford;exclusion;blacklisted"),
             paste("hg38;Tim Reddy;Duke;exclusion;blacklisted"),
             paste("hg38;Barbara Wold;Caltech;exclusion;blacklisted"),
             paste("hg38;Gene Yeo;UCSD;exclusion;blacklisted"),
             paste("mm10;Ross Hardison;PennState;exclusion;blacklisted"),
             paste("mm10;Ross Hardison;PennState;exclusion;blacklisted"),
             paste("mm10;Anshul Kundaje;Stanford;exclusion;blacklisted"),
             paste("mm10;Anshul Kundaje;Stanford;exclusion;blacklisted"),
             paste("mm10;Barbara Wold;Caltech;exclusion;blacklisted"),
             paste("mm9;Barbara Wold;Caltech;exclusion;blacklisted")),
    Notes = "")

write.csv(meta, file="inst/extdata/metadata.csv", row.names=FALSE)
